### ISSUE TITLE
syntax error during pull, circular dependencies

### ISSUE THREAD

**Issue by larshp** [abapify/fetch#1]
abapGit doesnt handle circular dependencies in the code. Personally I'd also consider it bad practice, as a consequence its not possible to copy paste the code into the system manually without first altering it, and later pasting the correct code

![image](https://github.com/user-attachments/assets/ef575a2d-27e0-43f2-b8c6-a4757218ef52)

![image](https://github.com/user-attachments/assets/4b79c9c0-6e64-459f-a72f-8574f275fc7d)

**Comment by larshp** [comment]
I'm updating https://rules.abaplint.org/cyclic_oo/ to discover this scenario

**Comment by larshp** [comment]
![image](https://github.com/user-attachments/assets/63f335e8-f4b0-423e-b1d3-58f44f3c6410)

**Comment by ThePlenkov** [comment]
should be good now. Moved to zif_fetch_destination_types interface
